---
title: "CO2 Emissions 1997"
author: "Team 2"
date: "2024-03-18"
output: 'pdf_document'  
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

\center _POV: 1997_ \center

## Context 

Climate science has emerged as a leading field of interest in the 20th century. Efforts to bring awareness to the impact of human intervention on the environment, such as the burning of fossil fuels, have proved fruitful. The Intergovernmental Panel on Climate Change (IPCC) has reinforced these efforts. In 1990 they released the First Climate Assessment Report stating that "human activities are substantially increasing the atmospheric concentration of greenhouse gases" (IPCC, 1990). Greenhouse gases are a group of gases, such as carbon dioxide, methane, and nitrous oxide, that when present in higher concentrations in the atmosphere, raise the surface temperate of the Earth. Carbon dioxide is the most abundant greenhouse gas that is produced from human activity, namely energy production via fossil fuel combustion. Since the industrial revolution, energy consumption from petroleum and natural gas sources has risen dramatically. This report aims to investigate the following questions: How have the levels of atmospheric CO2 changed over time? And, is there an identifiable pattern that will persist into the future? Forecasting atmospheric carbon dioxide concentrations allows scientists to measure the corresponding impact to the global environment and justify the need for human intervention in the opposite direction. 

- What has been studied so far? Svante Arrhenius & Charles Keeling 

## Data and Exploration 

- The CO2 data set consists of 468 observations. Each observation represents the monthly total atmospheric concentration of CO2, measured in parts per million (ppm) and collected at the Mauna Loa Observatory in Hawaii. The data ranges from January 1959 to December 1997. The data is originally sourced from the Scripps institute and was collected as part of the Scripps CO2 Program. Observations for February, March, and April 1964 were unavailable so the values in the data et were generated via linear interpolation between the observations for January and May 1964. 
- How is it measured/collected? 
- Plot what data looks like to justify concern 

## Models and Forecasts

- Why modeling is important to aid understanding? 
- Empirical evidence 

### *Linear Model*

- Functional form 
- Results 
- Interpretation/evaluation? 

### *ARIMA Model*

- Functional form 
- Results 

### *Forecasts*

- Forecasts 
- Interpretation/evaluation? 

## Conclusions 

- Implications 



